# Generated by Django 5.2.11 on 2026-03-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlob',
            fields=[
                ('sha256_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('size', models.BigIntegerField(help_text='File size in bytes.')),
                ('reference_count', models.IntegerField(default=1)),
                ('storage_backend', models.CharField(default='local', max_length=32)),
                ('storage_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'content blob',
                'verbose_name_plural': 'content blobs',
            },
        ),
    ]
