# Generated by Django 5.2.11 on 2026-03-03 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_organization_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('icon', models.CharField(default='bi-link-45deg', max_length=64)),
                ('is_directional', models.BooleanField(default=True, help_text='If True, the relationship has a direction (source -> target).')),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in types cannot be deleted.')),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'relationship type',
                'verbose_name_plural': 'relationship types',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='documents.document')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='relationships.relationshiptype')),
            ],
            options={
                'verbose_name': 'document relationship',
                'verbose_name_plural': 'document relationships',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source_document', 'target_document', 'relationship_type'), name='unique_document_relationship')],
            },
        ),
    ]
