# Generated by Django 5.2.11 on 2026-03-02 16:04

import django.core.validators
import django.db.models.deletion
import mptt.fields
import organization.models.storage_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.cabinet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cabinet',
                'verbose_name_plural': 'cabinets',
                'ordering': ['tree_id', 'lft'],
                'constraints': [models.UniqueConstraint(fields=('name', 'parent'), name='unique_cabinet_name_per_parent')],
            },
        ),
        migrations.CreateModel(
            name='Correspondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('match', models.CharField(blank=True, default='', help_text='Pattern to match against document content.', max_length=512)),
                ('matching_algorithm', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Any word'), (2, 'All words'), (3, 'Literal'), (4, 'Regular expression'), (5, 'Fuzzy match'), (6, 'Auto (ML-based)')], default=0)),
                ('is_insensitive', models.BooleanField(default=True, help_text='Case-insensitive matching.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'correspondent',
                'verbose_name_plural': 'correspondents',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_correspondent_name')],
            },
        ),
        migrations.CreateModel(
            name='StoragePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('match', models.CharField(blank=True, default='', help_text='Pattern to match against document content.', max_length=512)),
                ('matching_algorithm', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Any word'), (2, 'All words'), (3, 'Literal'), (4, 'Regular expression'), (5, 'Fuzzy match'), (6, 'Auto (ML-based)')], default=0)),
                ('is_insensitive', models.BooleanField(default=True, help_text='Case-insensitive matching.')),
                ('path', models.CharField(help_text='Jinja2 template for file path. Available variables: created_year, created_month, correspondent, title, document_type, added_year, added_month, original_filename, asn.', max_length=1024, validators=[organization.models.storage_path.validate_path_template])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'storage path',
                'verbose_name_plural': 'storage paths',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_storage_path_name')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('match', models.CharField(blank=True, default='', help_text='Pattern to match against document content.', max_length=512)),
                ('matching_algorithm', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Any word'), (2, 'All words'), (3, 'Literal'), (4, 'Regular expression'), (5, 'Fuzzy match'), (6, 'Auto (ML-based)')], default=0)),
                ('is_insensitive', models.BooleanField(default=True, help_text='Case-insensitive matching.')),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for tag display.', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color (e.g. #3b82f6).', regex='^#[0-9a-fA-F]{6}$')])),
                ('is_inbox_tag', models.BooleanField(default=False, help_text='Automatically assigned to new documents for triage.')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.tag')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['tree_id', 'lft'],
                'constraints': [models.UniqueConstraint(fields=('name', 'parent'), name='unique_tag_name_per_parent')],
            },
        ),
    ]
