# Generated by Django 5.2.11 on 2026-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_custom_fields_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldinstance',
            name='value_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
