# Generated by Django 5.2.11 on 2026-03-02 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_organization_fields'),
        ('organization', '0003_fix_value_bool_blank'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('set_correspondent', 'Set Correspondent'), ('set_document_type', 'Set Document Type'), ('set_storage_path', 'Set Storage Path'), ('set_custom_field', 'Set Custom Field'), ('assign_permissions', 'Assign Permissions'), ('send_email', 'Send Email'), ('webhook', 'Webhook'), ('launch_workflow', 'Launch Workflow'), ('run_script', 'Run Script')], max_length=32)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Action-specific configuration as JSON.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'workflow action',
                'verbose_name_plural': 'workflow actions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('consumption', 'Consumption'), ('document_added', 'Document Added'), ('document_updated', 'Document Updated'), ('scheduled', 'Scheduled')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('filter_filename', models.CharField(blank=True, default='', help_text='Glob pattern to match against the document filename.', max_length=256)),
                ('filter_path', models.CharField(blank=True, default='', help_text='Glob pattern to match against the source file path.', max_length=512)),
                ('filter_custom_field_query', models.JSONField(blank=True, default=dict)),
                ('match_pattern', models.CharField(blank=True, default='', help_text='Text pattern to match against document title/content.', max_length=256)),
                ('matching_algorithm', models.IntegerField(choices=[(0, 'None'), (1, 'Any word'), (2, 'All words'), (3, 'Exact match'), (4, 'Regular expression'), (5, 'Fuzzy match')], default=0)),
                ('schedule_interval_minutes', models.PositiveIntegerField(blank=True, help_text='Interval in minutes for scheduled triggers.', null=True)),
                ('filter_has_correspondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.correspondent')),
                ('filter_has_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documenttype')),
                ('filter_has_tags', models.ManyToManyField(blank=True, related_name='+', to='organization.tag')),
            ],
            options={
                'verbose_name': 'workflow trigger',
                'verbose_name_plural': 'workflow triggers',
                'ordering': ['type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=192)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order relative to other rules.')),
                ('actions', models.ManyToManyField(blank=True, related_name='rules', to='workflows.workflowaction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('triggers', models.ManyToManyField(blank=True, related_name='rules', to='workflows.workflowtrigger')),
            ],
            options={
                'verbose_name': 'workflow rule',
                'verbose_name_plural': 'workflow rules',
                'ordering': ['order', 'name'],
            },
        ),
    ]
