# Generated by Django 5.2.13 on 2026-04-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowaction_workflowtrigger_workflowrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtransitionfield',
            name='choices',
            field=models.JSONField(blank=True, help_text='List of options for SELECT fields, e.g. ["opt1", "opt2"].', null=True),
        ),
        migrations.AlterField(
            model_name='workflowtransitionfield',
            name='field_type',
            field=models.CharField(choices=[('char', 'Character'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('text', 'Text'), ('select', 'Select')], default='char', max_length=16),
        ),
    ]
