# Generated by Django 5.2.11 on 2026-03-02 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('task_name', models.CharField(default='document_consumption', max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], db_index=True, default='pending', max_length=16)),
                ('progress', models.FloatField(default=0.0, help_text='Progress from 0.0 to 1.0')),
                ('status_message', models.CharField(blank=True, default='', max_length=512)),
                ('result', models.TextField(blank=True, default='')),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_tasks', to='documents.document')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'processing task',
                'verbose_name_plural': 'processing tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
