# Generated by Django 5.2.11 on 2026-03-03 03:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_organization_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=32)),
                ('signing_order', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=16)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='esignatures/certificates/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signature request',
                'verbose_name_plural': 'signature requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', max_length=32)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('verification_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('none', 'None')], default='email', max_length=16)),
                ('verification_code', models.CharField(blank=True, default='', max_length=16)),
                ('viewed_pages', models.JSONField(blank=True, default=list)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='esignatures.signaturerequest')),
            ],
            options={
                'verbose_name': 'signer',
                'verbose_name_plural': 'signers',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SignatureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField()),
                ('x', models.FloatField(help_text='X coordinate (0.0-1.0)')),
                ('y', models.FloatField(help_text='Y coordinate (0.0-1.0)')),
                ('width', models.FloatField(help_text='Width (0.0-1.0)')),
                ('height', models.FloatField(help_text='Height (0.0-1.0)')),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials'), ('date', 'Date'), ('text', 'Text'), ('checkbox', 'Checkbox')], max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('value', models.TextField(blank=True, default='')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='esignatures.signaturerequest')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='esignatures.signer')),
            ],
            options={
                'verbose_name': 'signature field',
                'verbose_name_plural': 'signature fields',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SignatureAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('page_viewed', 'Page Viewed'), ('signed', 'Signed'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reminder_sent', 'Reminder Sent')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='esignatures.signaturerequest')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='esignatures.signer')),
            ],
            options={
                'verbose_name': 'signature audit event',
                'verbose_name_plural': 'signature audit events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(fields=('request', 'email'), name='unique_signer_per_request'),
        ),
    ]
