# Generated by Django 5.2.11 on 2026-03-02 20:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_organization_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=192)),
                ('initial', models.BooleanField(default=False, help_text='Whether this is the starting state for new instances.')),
                ('final', models.BooleanField(default=False, help_text='Whether reaching this state completes the workflow.')),
                ('completion', models.PositiveSmallIntegerField(default=0, help_text='Completion percentage (0-100) for progress tracking.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'workflow state',
                'verbose_name_plural': 'workflow states',
                'ordering': ['workflow', 'label'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=192)),
                ('enabled', models.BooleanField(default=True)),
                ('when', models.CharField(choices=[('on_entry', 'On entry'), ('on_exit', 'On exit')], default='on_entry', max_length=16)),
                ('backend_path', models.CharField(help_text='Dotted path to the action backend class.', max_length=256)),
                ('backend_data', models.JSONField(blank=True, default=dict, help_text='JSON configuration for the action backend.')),
                ('condition', models.TextField(blank=True, default='', help_text='Optional condition expression for this action.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order (lower runs first).')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflowstate')),
            ],
            options={
                'verbose_name': 'state action',
                'verbose_name_plural': 'state actions',
                'ordering': ['state', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=192)),
                ('internal_name', models.SlugField(max_length=192, unique=True)),
                ('auto_launch', models.BooleanField(default=False, help_text='Automatically launch this workflow for matching document types.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_types', models.ManyToManyField(blank=True, help_text='Document types that this workflow applies to.', related_name='workflow_templates', to='documents.documenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workflow template',
                'verbose_name_plural': 'workflow templates',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflows.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Workflow context data (accumulated transition field values).')),
                ('launched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='documents.document')),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.workflowtemplate')),
            ],
            options={
                'verbose_name': 'workflow instance',
                'verbose_name_plural': 'workflow instances',
                'ordering': ['-launched_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=192)),
                ('condition', models.TextField(blank=True, default='', help_text='Python expression evaluated to determine if transition is available.')),
                ('destination_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.workflowstate')),
                ('origin_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflowtemplate')),
            ],
            options={
                'verbose_name': 'workflow transition',
                'verbose_name_plural': 'workflow transitions',
                'ordering': ['workflow', 'label'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStateEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('amount', models.PositiveIntegerField(help_text='Time duration before escalation triggers.')),
                ('unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='days', max_length=16)),
                ('condition', models.TextField(blank=True, default='', help_text='Optional condition expression for this escalation.')),
                ('comment', models.CharField(blank=True, default='', help_text='Comment added to the log when escalation triggers.', max_length=512)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority (lower is checked first).')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='workflows.workflowstate')),
                ('transition', models.ForeignKey(help_text='Transition to execute when escalation triggers.', on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rules', to='workflows.workflowtransition')),
            ],
            options={
                'verbose_name': 'state escalation',
                'verbose_name_plural': 'state escalations',
                'ordering': ['state', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstanceLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, default='')),
                ('transition_field_values', models.JSONField(blank=True, default=dict, help_text='Values submitted for transition fields.')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='workflows.workflowinstance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowtransition')),
            ],
            options={
                'verbose_name': 'workflow log entry',
                'verbose_name_plural': 'workflow log entries',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal field name.', max_length=128)),
                ('label', models.CharField(help_text='Display label.', max_length=192)),
                ('field_type', models.CharField(choices=[('char', 'Character'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('text', 'Text')], default='char', max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('default', models.CharField(blank=True, default='', max_length=512)),
                ('help_text', models.CharField(blank=True, default='', max_length=512)),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workflows.workflowtransition')),
            ],
            options={
                'verbose_name': 'transition field',
                'verbose_name_plural': 'transition fields',
                'ordering': ['transition', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('workflow', 'label'), name='unique_state_label_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(fields=('document', 'workflow'), name='unique_workflow_per_document'),
        ),
    ]
