"""Constants for the AI module."""

# LLM providers
PROVIDER_OPENAI = "openai"
PROVIDER_OLLAMA = "ollama"
PROVIDER_DISABLED = "disabled"

SUPPORTED_PROVIDERS = [PROVIDER_OPENAI, PROVIDER_OLLAMA]

# Default models
DEFAULT_OPENAI_MODEL = "gpt-4o-mini"
DEFAULT_OLLAMA_MODEL = "llama3"
DEFAULT_EMBEDDING_MODEL_OPENAI = "text-embedding-3-small"
DEFAULT_EMBEDDING_MODEL_OLLAMA = "nomic-embed-text"

# Token limits
MAX_CONTEXT_TOKENS = 8000
MAX_PROMPT_TOKENS = 4000
CHUNK_SIZE = 500
CHUNK_OVERLAP = 50

# Embedding dimensions
EMBEDDING_DIM_OPENAI = 1536
EMBEDDING_DIM_OLLAMA = 768
DEFAULT_EMBEDDING_DIM = 1536

# Vector search defaults
VECTOR_SEARCH_K = 10
HYBRID_KEYWORD_WEIGHT = 0.4
HYBRID_SEMANTIC_WEIGHT = 0.6

# Chat
MAX_CHAT_HISTORY = 10
RAG_TOP_K = 5
