# Generated by Django 5.2.13 on 2026-04-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_source_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('watch_folder', 'Watch Folder'), ('email', 'Email (IMAP)'), ('staging', 'Staging Folder'), ('s3', 'S3 Bucket'), ('scanner', 'SANE Scanner')], max_length=32),
        ),
    ]
