# Generated by Django 5.2.11 on 2026-03-03 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_organization_fields'),
        ('organization', '0003_fix_value_bool_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneOCRTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('sample_page_image', models.ImageField(blank=True, help_text='Sample page image used to define zones visually.', null=True, upload_to='zone_ocr/samples/')),
                ('page_number', models.PositiveIntegerField(default=1, help_text='The page number this template applies to (1-indexed).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is used during document processing.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'zone OCR template',
                'verbose_name_plural': 'zone OCR templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZoneOCRField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('date', 'Date'), ('integer', 'Integer'), ('float', 'Float'), ('monetary', 'Monetary'), ('boolean', 'Boolean')], help_text='Expected data type for the extracted value.', max_length=16)),
                ('bounding_box', models.JSONField(default=dict, help_text='Bounding box as percentages: {x, y, width, height}.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('preprocessing', models.CharField(choices=[('none', 'None'), ('numeric_only', 'Numeric Only'), ('alpha_only', 'Alpha Only'), ('date_parse', 'Date Parse'), ('currency_parse', 'Currency Parse')], default='none', help_text='Preprocessing to apply to the raw OCR text.', max_length=32)),
                ('validation_regex', models.CharField(blank=True, default='', help_text='Optional regex to validate extracted values.', max_length=512)),
                ('custom_field', models.ForeignKey(blank=True, help_text='If set, extracted value is written to this custom field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_ocr_fields', to='organization.customfield')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='zone_ocr.zoneocrtemplate')),
            ],
            options={
                'verbose_name': 'zone OCR field',
                'verbose_name_plural': 'zone OCR fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ZoneOCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_value', models.TextField(default='', help_text='The raw value extracted by OCR.')),
                ('confidence', models.FloatField(default=0.0, help_text='OCR confidence score (0.0 to 1.0).')),
                ('reviewed', models.BooleanField(default=False, help_text='Whether a human has reviewed this result.')),
                ('corrected_value', models.TextField(blank=True, default='', help_text='User-corrected value, if different from extracted_value.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_ocr_results', to='documents.document')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='zone_ocr.zoneocrfield')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_ocr_reviews', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='zone_ocr.zoneocrtemplate')),
            ],
            options={
                'verbose_name': 'zone OCR result',
                'verbose_name_plural': 'zone OCR results',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document', 'template', 'field'), name='unique_zone_result_per_document_field')],
            },
        ),
        migrations.AddConstraint(
            model_name='zoneocrfield',
            constraint=models.UniqueConstraint(fields=('template', 'name'), name='unique_zone_field_name_per_template'),
        ),
    ]
