# Generated by Django 5.2.11 on 2026-03-02 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0003_add_organization_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_documents', models.PositiveIntegerField(blank=True, help_text='Maximum number of documents allowed. Null = unlimited.', null=True)),
                ('max_storage_bytes', models.PositiveBigIntegerField(blank=True, help_text='Maximum storage in bytes. Null = unlimited.', null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quota',
                'verbose_name_plural': 'quotas',
                'ordering': ['user', 'group'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('document_added', 'Document Added'), ('document_processed', 'Document Processed'), ('processing_failed', 'Processing Failed'), ('workflow_transition', 'Workflow Transition'), ('comment_added', 'Comment Added'), ('share_accessed', 'Share Accessed'), ('retention_warning', 'Retention Warning'), ('quota_warning', 'Quota Warning')], max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(blank=True, default='')),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='notificatio_user_id_4fcc58_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('document_added', 'Document Added'), ('document_processed', 'Document Processed'), ('processing_failed', 'Processing Failed'), ('workflow_transition', 'Workflow Transition'), ('comment_added', 'Comment Added'), ('share_accessed', 'Share Accessed'), ('retention_warning', 'Retention Warning'), ('quota_warning', 'Quota Warning')], max_length=32)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('webhook', 'Webhook')], default='in_app', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'ordering': ['user', 'event_type', 'channel'],
                'unique_together': {('user', 'event_type', 'channel')},
            },
        ),
    ]
