# Generated by Django 5.2.11 on 2026-03-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail_path',
            field=models.CharField(blank=True, default='', help_text='Storage path to the WebP thumbnail.', max_length=1024),
        ),
    ]
