# Generated by Django 5.2.11 on 2026-03-02 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_thumbnail_path'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='organization.cabinet'),
        ),
        migrations.AddField(
            model_name='document',
            name='correspondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='organization.correspondent'),
        ),
        migrations.AddField(
            model_name='document',
            name='storage_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='organization.storagepath'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='organization.tag'),
        ),
    ]
