# Generated by Django 5.2.13 on 2026-04-16 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_suggested_fields'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='suggested_correspondent',
        ),
        migrations.RemoveField(
            model_name='document',
            name='suggested_document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='suggested_tags',
        ),
        migrations.AddField(
            model_name='document',
            name='is_obsolete',
            field=models.BooleanField(db_index=True, default=False, help_text='Set automatically when another document supersedes this one.'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='blob',
            field=models.ForeignKey(blank=True, help_text='Link to content-addressed storage blob.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.contentblob'),
        ),
    ]
