apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docvault.fullname" . }}
  labels:
    {{- include "docvault.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ include "docvault.databaseUrl" . | quote }}
  REDIS_URL: {{ include "docvault.redisUrl" . | quote }}
  DJANGO_SETTINGS_MODULE: {{ .Values.env.DJANGO_SETTINGS_MODULE | default "docvault.settings.production" | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.env.DJANGO_ALLOWED_HOSTS | default "*" | quote }}
  DJANGO_SECURE_SSL_REDIRECT: {{ .Values.env.DJANGO_SECURE_SSL_REDIRECT | default "false" | quote }}
  STORAGE_BACKEND: {{ .Values.env.STORAGE_BACKEND | default "local" | quote }}
  MEDIA_ROOT: "/data/media"
  STATIC_ROOT: "/app/staticfiles"
  {{- if .Values.elasticsearch.enabled }}
  ELASTICSEARCH_ENABLED: "true"
  ELASTICSEARCH_URL: {{ .Values.elasticsearch.url | quote }}
  {{- end }}
  {{- range $key, $value := .Values.env }}
  {{- if and (ne $key "DJANGO_SECRET_KEY") (ne $key "DJANGO_SETTINGS_MODULE") (ne $key "DJANGO_ALLOWED_HOSTS") (ne $key "DJANGO_SECURE_SSL_REDIRECT") (ne $key "STORAGE_BACKEND") }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
