# Generated by Django 5.2.11 on 2026-03-02 03:11

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('content', models.TextField(blank=True, default='', help_text='OCR/extracted text content.')),
                ('original_filename', models.CharField(blank=True, default='', max_length=1024)),
                ('mime_type', models.CharField(blank=True, default='', max_length=256)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 checksum of the original file.', max_length=64)),
                ('archive_checksum', models.CharField(blank=True, default='', help_text='SHA-256 checksum of the archive (PDF/A) file.', max_length=64)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('filename', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('archive_filename', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('created', models.DateField(db_index=True, default=datetime.date.today, help_text='Document date (extracted or user-set).')),
                ('added', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date/time this document was ingested into the system.')),
                ('archive_serial_number', models.PositiveIntegerField(blank=True, help_text='Unique physical archive reference number.', null=True, unique=True)),
                ('language', models.CharField(default='en', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/files/')),
                ('filename', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=256)),
                ('encoding', models.CharField(blank=True, default='', max_length=64)),
                ('checksum', models.CharField(help_text='SHA-256 checksum.', max_length=64)),
                ('size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes.')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document file',
                'verbose_name_plural': 'document files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('trash_time_period', models.PositiveIntegerField(blank=True, help_text='Auto-trash documents of this type after this period.', null=True)),
                ('trash_time_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=16, null=True)),
                ('delete_time_period', models.PositiveIntegerField(blank=True, help_text='Auto-delete trashed documents after this period.', null=True)),
                ('delete_time_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=16, null=True)),
                ('match', models.CharField(blank=True, default='', help_text='Pattern to match against document content.', max_length=256)),
                ('matching_algorithm', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Any word'), (2, 'All words'), (3, 'Literal'), (4, 'Regular expression'), (5, 'Fuzzy match'), (6, 'Auto (ML-based)')], default=0)),
                ('is_insensitive', models.BooleanField(default=True, help_text='Case-insensitive matching.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document type',
                'verbose_name_plural': 'document types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttype'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='documents.document')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.documentfile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True, default='', help_text='OCR text for this page.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'verbose_name': 'document page',
                'verbose_name_plural': 'document pages',
                'ordering': ['page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['checksum'], name='documents_d_checksu_fd63d2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['archive_serial_number'], name='documents_d_archive_f223f4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['mime_type'], name='documents_d_mime_ty_29cc61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
