# Generated by Django 5.2.11 on 2026-03-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_organization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_held',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
