# Generated by Django 5.2.11 on 2026-03-03 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_organization_fields'),
        ('security', '0002_initial_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('confirmed', models.BooleanField(default=False, help_text='Whether the device has been confirmed with a valid OTP code.')),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='Hashed backup codes for account recovery.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP device',
                'verbose_name_plural': 'OTP devices',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_data', models.TextField(help_text='ASCII-armored GPG signature.')),
                ('key_id', models.CharField(help_text='GPG key ID used for signing.', max_length=64)),
                ('algorithm', models.CharField(default='RSA', max_length=32)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document')),
                ('signer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signatures', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signature',
                'verbose_name_plural': 'signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('download', 'Download'), ('sign', 'Sign'), ('verify', 'Verify'), ('otp_setup', 'OTP Setup'), ('otp_disable', 'OTP Disable'), ('password_change', 'Password Change'), ('permission_change', 'Permission Change')], db_index=True, max_length=32)),
                ('model_type', models.CharField(blank=True, db_index=True, default='', help_text="Model class name (e.g., 'Document', 'User').", max_length=64)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='security_au_user_id_787334_idx'), models.Index(fields=['action', 'timestamp'], name='security_au_action_451b2c_idx')],
            },
        ),
    ]
