apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docvault.fullname" . }}
  labels:
    {{- include "docvault.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.secretEnv.DJANGO_SECRET_KEY | default .Values.env.DJANGO_SECRET_KEY | b64enc | quote }}
  {{- range $key, $value := .Values.secretEnv }}
  {{- if ne $key "DJANGO_SECRET_KEY" }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
