# Generated by Django 5.2.11 on 2026-03-03 04:03

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_document_is_held'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location_type', models.CharField(choices=[('building', 'Building'), ('room', 'Room'), ('cabinet', 'Cabinet'), ('shelf', 'Shelf'), ('box', 'Box')], max_length=32)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='physical_records.physicallocation')),
            ],
            options={
                'verbose_name': 'physical location',
                'verbose_name_plural': 'physical locations',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(blank=True, default='', max_length=128)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_record', to='documents.document')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='physical_records.physicallocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'physical record',
                'verbose_name_plural': 'physical records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestructionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destroyed_at', models.DateTimeField()),
                ('method', models.CharField(choices=[('shredding', 'Shredding'), ('incineration', 'Incineration'), ('pulping', 'Pulping'), ('other', 'Other')], max_length=32)),
                ('witness', models.CharField(blank=True, default='', max_length=256)),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='physical_records/certificates/')),
                ('notes', models.TextField(blank=True, default='')),
                ('destroyed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destruction_certificates', to=settings.AUTH_USER_MODEL)),
                ('physical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destruction_certificates', to='physical_records.physicalrecord')),
            ],
            options={
                'verbose_name': 'destruction certificate',
                'verbose_name_plural': 'destruction certificates',
                'ordering': ['-destroyed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargeOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('expected_return', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('checked_out', 'Checked Out'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='checked_out', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_outs', to=settings.AUTH_USER_MODEL)),
                ('physical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_outs', to='physical_records.physicalrecord')),
            ],
            options={
                'verbose_name': 'charge out',
                'verbose_name_plural': 'charge outs',
                'ordering': ['-checked_out_at'],
            },
        ),
    ]
