# Generated by Django 5.2.11 on 2026-03-03 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_organization_fields'),
        ('search', '0001_saved_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=512, unique=True)),
                ('boost_fields', models.JSONField(blank=True, default=dict, help_text='Field boost overrides, e.g. {"title": 3.0}.')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hidden_documents', models.ManyToManyField(blank=True, related_name='hidden_in_curations', to='documents.document')),
                ('pinned_documents', models.ManyToManyField(blank=True, related_name='pinned_in_curations', to='documents.document')),
            ],
            options={
                'verbose_name': 'search curation',
                'verbose_name_plural': 'search curations',
                'ordering': ['query_text'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=512)),
                ('results_count', models.IntegerField(default=0)),
                ('click_position', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('clicked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'search query',
                'verbose_name_plural': 'search queries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.JSONField(default=list, help_text='List of synonymous terms.')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'search synonym',
                'verbose_name_plural': 'search synonyms',
                'ordering': ['created_at'],
            },
        ),
    ]
