# Generated by Django 5.2.11 on 2026-03-03 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_organization_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.PositiveIntegerField()),
                ('annotation_type', models.CharField(choices=[('highlight', 'Highlight'), ('underline', 'Underline'), ('strikethrough', 'Strikethrough'), ('sticky_note', 'Sticky Note'), ('freehand', 'Freehand'), ('rectangle', 'Rectangle'), ('text_box', 'Text Box'), ('rubber_stamp', 'Rubber Stamp')], max_length=32)),
                ('coordinates', models.JSONField(default=dict, help_text='Normalised coordinate data (all values 0.0-1.0).')),
                ('content', models.TextField(blank=True, default='', help_text='Text content for sticky notes, text boxes, or stamp labels.')),
                ('color', models.CharField(default='#FFFF00', help_text='Hex colour code, e.g. #FFFF00.', max_length=7)),
                ('opacity', models.FloatField(default=0.3, help_text='Opacity value between 0.0 and 1.0.')),
                ('is_private', models.BooleanField(default=False, help_text='Private annotations are visible only to the author and staff.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'annotation',
                'verbose_name_plural': 'annotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='annotations.annotation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'annotation reply',
                'verbose_name_plural': 'annotation replies',
                'ordering': ['created_at'],
            },
        ),
    ]
