# Generated by Django 5.2.11 on 2026-03-03 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_document_is_held'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('matter_number', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('released', 'Released')], db_index=True, default='draft', max_length=32)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_holds', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'legal hold',
                'verbose_name_plural': 'legal holds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalHoldCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_type', models.CharField(choices=[('custodian', 'Custodian'), ('date_range', 'Date Range'), ('tag', 'Tag'), ('document_type', 'Document Type'), ('search_query', 'Search Query'), ('cabinet', 'Cabinet'), ('specific_documents', 'Specific Documents')], max_length=32)),
                ('value', models.JSONField(default=dict)),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='legal_hold.legalhold')),
            ],
            options={
                'verbose_name': 'legal hold criterion',
                'verbose_name_plural': 'legal hold criteria',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='LegalHoldCustodian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodians', to='legal_hold.legalhold')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_hold_custodianships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'legal hold custodian',
                'verbose_name_plural': 'legal hold custodians',
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('hold', 'user'), name='unique_hold_custodian')],
            },
        ),
        migrations.CreateModel(
            name='LegalHoldDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to='documents.document')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_documents', to='legal_hold.legalhold')),
            ],
            options={
                'verbose_name': 'legal hold document',
                'verbose_name_plural': 'legal hold documents',
                'ordering': ['-held_at'],
                'constraints': [models.UniqueConstraint(fields=('hold', 'document'), name='unique_hold_document')],
            },
        ),
    ]
