# Generated by Django 5.2.11 on 2026-03-02 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_organization_fields'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('longtext', 'Long Text'), ('url', 'URL'), ('date', 'Date'), ('datetime', 'Date & Time'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('monetary', 'Monetary'), ('documentlink', 'Document Link'), ('select', 'Select'), ('multiselect', 'Multi-Select')], help_text='The data type for this field.', max_length=16)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Type-specific configuration. For SELECT/MULTISELECT: {"options": ["opt1", "opt2"]}. For STRING: {"max_length": 256}.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'custom field',
                'verbose_name_plural': 'custom fields',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(null=True)),
                ('value_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_monetary', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('value_document_ids', models.JSONField(blank=True, default=list, help_text='List of document IDs for DOCUMENTLINK type.')),
                ('value_select', models.JSONField(blank=True, default=list, help_text='Selected value(s) for SELECT/MULTISELECT.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_instances', to='documents.document')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='organization.customfield')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'custom field instance',
                'verbose_name_plural': 'custom field instances',
                'ordering': ['field__name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False, help_text='Whether this field is required for the document type.')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type_assignments', to='organization.customfield')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_assignments', to='documents.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('label', models.CharField(blank=True, default='', help_text='Human-readable label for display.', max_length=256)),
                ('default', models.CharField(blank=True, default='', help_text='Jinja2 template for default value.', max_length=512)),
                ('lookup', models.TextField(blank=True, default='', help_text='Jinja2 template for populating dropdown options (one per line).')),
                ('validation', models.CharField(blank=True, default='', help_text='Dotted path to a validator function, or built-in name.', max_length=256)),
                ('parser', models.CharField(blank=True, default='', help_text='Dotted path to a parser function.', max_length=256)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'metadata type',
                'verbose_name_plural': 'metadata types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False, help_text='Whether this metadata is required for the document type.')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_assignments', to='documents.documenttype')),
                ('metadata_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type_assignments', to='organization.metadatatype')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, default='', help_text='The metadata value (always stored as text, parsed on read).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_instances', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('metadata_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='organization.metadatatype')),
            ],
            options={
                'verbose_name': 'document metadata',
                'verbose_name_plural': 'document metadata',
                'ordering': ['metadata_type__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_custom_field_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='customfieldinstance',
            constraint=models.UniqueConstraint(fields=('document', 'field'), name='unique_custom_field_per_document'),
        ),
        migrations.AddConstraint(
            model_name='documenttypecustomfield',
            constraint=models.UniqueConstraint(fields=('document_type', 'custom_field'), name='unique_doctype_custom_field'),
        ),
        migrations.AddConstraint(
            model_name='metadatatype',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_metadata_type_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='documenttypemetadata',
            constraint=models.UniqueConstraint(fields=('document_type', 'metadata_type'), name='unique_doctype_metadata_type'),
        ),
        migrations.AddConstraint(
            model_name='documentmetadata',
            constraint=models.UniqueConstraint(fields=('document', 'metadata_type'), name='unique_metadata_per_document'),
        ),
    ]
