# Generated by Django 5.2.11 on 2026-03-03 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_organization_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('icon', models.CharField(default='bi-tag', max_length=64)),
                ('extraction_pattern', models.TextField(blank=True, default='', help_text='Optional regex pattern for custom extraction.')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'entity type',
                'verbose_name_plural': 'entity types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Normalized entity value.', max_length=512)),
                ('raw_value', models.CharField(help_text='Original text as it appeared in the document.', max_length=512)),
                ('confidence', models.FloatField(default=1.0)),
                ('start_offset', models.IntegerField(default=0)),
                ('end_offset', models.IntegerField(default=0)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='documents.document')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='entities.entitytype')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
                'ordering': ['entity_type', 'value'],
                'indexes': [models.Index(fields=['document', 'entity_type'], name='entities_en_documen_4fed6d_idx')],
            },
        ),
    ]
