# Generated by Django 5.2.11 on 2026-03-02 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('display_mode', models.CharField(choices=[('table', 'Table'), ('small_cards', 'Small Cards'), ('large_cards', 'Large Cards')], default='table', max_length=16)),
                ('display_fields', models.JSONField(blank=True, default=list, help_text='List of column names to display.')),
                ('sort_field', models.CharField(blank=True, default='created', max_length=64)),
                ('sort_reverse', models.BooleanField(default=True)),
                ('page_size', models.PositiveIntegerField(default=25)),
                ('show_on_dashboard', models.BooleanField(default=False)),
                ('show_in_sidebar', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved view',
                'verbose_name_plural': 'saved views',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedViewFilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('title_contains', 'Title contains'), ('content_contains', 'Content contains'), ('asn_is', 'ASN is'), ('correspondent_is', 'Correspondent is'), ('document_type_is', 'Document type is'), ('tag_is', 'Has tag'), ('tag_all', 'Has all tags'), ('tag_none', 'Has none of tags'), ('has_tags', 'Has any tags'), ('has_no_tags', 'Has no tags'), ('cabinet_is', 'Cabinet is'), ('has_correspondent', 'Has a correspondent'), ('has_no_correspondent', 'Has no correspondent'), ('has_document_type', 'Has a document type'), ('has_no_document_type', 'Has no document type'), ('created_after', 'Created after'), ('created_before', 'Created before'), ('added_after', 'Added after'), ('added_before', 'Added before'), ('language_is', 'Language is'), ('mime_type_is', 'MIME type is'), ('owner_is', 'Owner is'), ('has_custom_field', 'Has custom field'), ('custom_field_value', 'Custom field value'), ('filename_contains', 'Filename contains'), ('asn_greater_than', 'ASN greater than'), ('asn_less_than', 'ASN less than'), ('has_asn', 'Has ASN'), ('has_no_asn', 'Has no ASN')], max_length=32)),
                ('value', models.CharField(blank=True, default='', help_text='The filter value (e.g., tag ID, date, text).', max_length=512)),
                ('saved_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_rules', to='search.savedview')),
            ],
            options={
                'ordering': ['rule_type'],
            },
        ),
    ]
