# Generated by Django 5.2.11 on 2026-03-02 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_organization_fields'),
        ('organization', '0003_fix_value_bool_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192)),
                ('enabled', models.BooleanField(default=True)),
                ('imap_server', models.CharField(max_length=256)),
                ('port', models.PositiveIntegerField(default=993)),
                ('security', models.CharField(choices=[('none', 'None'), ('ssl', 'SSL'), ('starttls', 'STARTTLS')], default='ssl', max_length=16)),
                ('account_type', models.CharField(choices=[('imap', 'IMAP'), ('gmail_oauth', 'Gmail OAuth2'), ('outlook_oauth', 'Outlook OAuth2')], default='imap', max_length=32)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(blank=True, default='', help_text='IMAP password or app-specific password.', max_length=512)),
                ('oauth_client_id', models.CharField(blank=True, default='', max_length=512)),
                ('oauth_client_secret', models.CharField(blank=True, default='', max_length=512)),
                ('oauth_access_token', models.TextField(blank=True, default='')),
                ('oauth_refresh_token', models.TextField(blank=True, default='')),
                ('oauth_token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'mail account',
                'verbose_name_plural': 'mail accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192)),
                ('enabled', models.BooleanField(default=True)),
                ('folder', models.CharField(default='INBOX', max_length=256)),
                ('filter_from', models.CharField(blank=True, default='', max_length=256)),
                ('filter_subject', models.CharField(blank=True, default='', max_length=256)),
                ('filter_body', models.CharField(blank=True, default='', max_length=256)),
                ('filter_attachment_filename', models.CharField(blank=True, default='', help_text='Glob pattern for attachment filenames.', max_length=256)),
                ('maximum_age', models.PositiveIntegerField(default=30, help_text='Maximum age of emails to process in days.')),
                ('action', models.CharField(choices=[('download_attachment', 'Download Attachments'), ('process_email', 'Process Entire Email')], default='download_attachment', max_length=32)),
                ('processed_action', models.CharField(choices=[('mark_read', 'Mark as Read'), ('move_to_folder', 'Move to Folder'), ('delete', 'Delete'), ('flag', 'Flag/Star')], default='mark_read', max_length=16)),
                ('processed_folder', models.CharField(blank=True, default='', help_text="Folder to move processed emails to (if action is 'move_to_folder').", max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='sources.mailaccount')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documenttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='+', to='organization.tag')),
            ],
            options={
                'verbose_name': 'mail rule',
                'verbose_name_plural': 'mail rules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=192)),
                ('enabled', models.BooleanField(default=True)),
                ('source_type', models.CharField(choices=[('watch_folder', 'Watch Folder'), ('email', 'Email (IMAP)'), ('staging', 'Staging Folder'), ('s3', 'S3 Bucket')], max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documenttype')),
                ('owner', models.ForeignKey(blank=True, help_text='Default owner for documents ingested from this source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sources', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='+', to='organization.tag')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='WatchFolderSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Absolute path to watch directory.', max_length=1024)),
                ('polling_interval', models.PositiveIntegerField(default=300, help_text='Polling interval in seconds.')),
                ('consumed_action', models.CharField(choices=[('delete', 'Delete file'), ('move', 'Move to consumed directory'), ('nothing', 'Do nothing')], default='move', max_length=16)),
                ('consumed_directory', models.CharField(blank=True, default='', help_text="Directory to move consumed files to (if action is 'move').", max_length=1024)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_folder', to='sources.source')),
            ],
            options={
                'verbose_name': 'watch folder source',
                'verbose_name_plural': 'watch folder sources',
            },
        ),
    ]
